mogupro/game/src/SocketBase.h
=> Update : SocketBase作成

mogupro/game/src/SocketBase.h, mogupro/game/src/SocketID.h
=> Update : バグ修正と関数追加

mogupro/game/src/SocketBase.h
=> Update : exportでほかの構文判断をしているので名前変更

mogupro/game/include/Network/Packet/Event.hpp, mogupro/game/include/Network/Packet/Request.hpp, mogupro/game/include/Network/Packet/Response.hpp, mogupro/game/include/Network/cEventManager.h, mogupro/game/include/Network/cRequestManager.h, mogupro/game/include/Network/cResponseManager.h, mogupro/game/src/Network/cEventManager.cpp, mogupro/game/src/Network/cRequestManager.cpp, mogupro/game/src/Network/cResponseManager.cpp, mogupro/game/src/Network/cUDPManager.cpp
これで全てのパケットが有効になりました。
後はパケット自体の構成次第です。
=> pmakeでマネージャー系を更新しました。

mogupro/game/include/Network/Packet/Event/cEveGetJem.h, mogupro/game/include/Network/Packet/Event/cEvePlayerDeath.h, mogupro/game/include/Network/Packet/Event/cEvePlayerRobJem.h, mogupro/game/include/Network/Packet/Event/cEveString.h, mogupro/game/include/Network/Packet/Request/cReqCheckBrakeBlocks.h, mogupro/game/include/Network/Packet/Request/cReqCheckGetJem.h, mogupro/game/include/Network/Packet/Request/cReqCheckPlayerDeath.h, mogupro/game/include/Network/Packet/Request/cReqCheckPlayerRobJem.h, mogupro/game/include/Network/Packet/Request/cReqCheckSetQuarry.h, mogupro/game/include/Network/Packet/Request/cReqGetJemPoint.h, mogupro/game/include/Network/Packet/Request/cReqGetJemSeed.h, mogupro/game/include/Network/Packet/Request/cReqPlayer.h, mogupro/game/include/Network/Packet/Request/cReqString.h, mogupro/game/include/Network/Packet/Response/cResCheckBrakeBlocks.h, mogupro/game/include/Network/Packet/Response/cResCheckGetJem.h, mogupro/game/include/Network/Packet/Response/cResCheckPlayerDeath.h, mogupro/game/include/Network/Packet/Response/cResCheckPlayerRobJem.h, mogupro/game/include/Network/Packet/Response/cResCheckSetQuarry.h, mogupro/game/include/Network/Packet/Response/cResGetJemPoint.h, mogupro/game/include/Network/Packet/Response/cResGetJemSeed.h, mogupro/game/include/Network/Packet/Response/cResPlayer.h, mogupro/game/include/Network/Packet/Response/cResString.h, mogupro/game/pmake/TEMPLATE.h
importとexportを噛ませるのでいらないですね。
パケットヘッダーは使ったままです。
=> "pragma pack"を使わないようにしました。

mogupro/game/include/Network/PackFunction.hpp, mogupro/game/include/Network/Packet/Request/cReqPlayer.h, mogupro/game/include/Network/cRequestManager.h, mogupro/game/src/Network/Packet/Request/cReqPlayer.cpp
=> Update : cReqPlayerにImport、Export追加

mogupro/game/include/Network/PackFunction.hpp, mogupro/game/include/Network/Packet/Request/cReqPlayer.h, mogupro/game/include/Scene/cSceneBase.h, mogupro/game/include/Scene/cSceneManager.h, mogupro/game/include/Utility/cTimeMeasurement.h, mogupro/game/src/Network/Packet/Request/cReqPlayer.cpp, mogupro/game/src/Utility/cTimeMeasurement.cpp
=> Update : SceneManager・TimeMeasurementの追加 PackFuinctionの修正、cReqPlayerの変数名を変更

mogupro/game/include/Game/Field/UnderGround/cBlock.h, mogupro/game/include/Game/Field/UnderGround/cUnderGround.h, mogupro/game/include/Game/Field/cFieldManager.h, mogupro/game/src/Game/Field/UnderGround/cBlock.cpp, mogupro/game/src/Game/Field/UnderGround/cUnderGround.cpp, mogupro/game/src/Game/Field/cFieldManager.cpp
=> ブロックのメッシュを一つのTriMeshにまとめました。

mogupro/game/include/Scene/Member/cTest.h, mogupro/game/include/Scene/cSceneBase.h, mogupro/game/src/Scene/Member/cTest.cpp
=> Update : Scene試し運用

mogupro/game/include/Scene/Member/cTest.h, mogupro/game/include/Scene/cSceneBase.h, mogupro/game/include/Scene/cSceneManager.h, mogupro/game/src/Scene/Member/cTest.cpp
=> Update : いったん作業おわり　ゆうだいあとはよろしくな！

mogupro/game/include/Scene/Member/cTest.h, mogupro/game/src/Scene/Member/cTest.cpp
=> Update : 修正

mogupro/game/include/Strategy/StrategyObject/cCannon.h, mogupro/game/include/Strategy/StrategyObject/cStrategyObjectBase.h, mogupro/game/include/Strategy/cStrategyManager.h, mogupro/game/src/Strategy/StrategyObject/cCannon.cpp, mogupro/game/src/Strategy/StrategyObject/cDrill.cpp, mogupro/game/src/Strategy/cStrategyManager.cpp
=> Drill base

mogupro/game/include/Game/cCameraManager.h, mogupro/game/src/Game/cCameraManager.cpp, mogupro/game/src/gameApp.cpp
ついでにgameAppでbind unbindするようにしておきました。
=> カメラマネージャーのネームスペース二重問題を解決。

mogupro/game/include/Collision/Collision.h, mogupro/game/include/Collision/cAABBCollider.h, mogupro/game/include/Collision/cColliderBase.h, mogupro/game/include/Collision/cCollisionManager.h, mogupro/game/include/Collision/cCollisionObject.h, mogupro/game/include/Collision/cRigidBody.h, mogupro/game/include/Utility/cSingletonAble.h, mogupro/game/src/Collision/Collision.cpp, mogupro/game/src/Collision/cAABBCollider.cpp, mogupro/game/src/Collision/cColliderBase.cpp, mogupro/game/src/Collision/cCollisionManager.cpp, mogupro/game/src/Collision/cCollisionObject.cpp, mogupro/game/src/Collision/cRigidBody.cpp
マイクラと同じ当たり判定です。
動的なオブジェクト同士の当たり判定がちょっとやばいかも。
要調整です。
そのうちBulletに移行するかもです。
=> 当たり判定空間を作成しました。

mogupro/game/include/Collision/cAABBCollider.h, mogupro/game/include/Collision/cColliderBase.h, mogupro/game/include/Collision/cCollisionManager.h, mogupro/game/include/Collision/cFallBlockSimple.h, mogupro/game/include/Collision/cRigidBody.h, mogupro/game/include/Collision/cStaticBlockSimple.h, mogupro/game/include/Scene/Member/cGameMain.h, mogupro/game/src/Collision/Collision.cpp, mogupro/game/src/Collision/cAABBCollider.cpp, mogupro/game/src/Collision/cColliderBase.cpp, mogupro/game/src/Collision/cCollisionManager.cpp, mogupro/game/src/Collision/cFallBlockSimple.cpp, mogupro/game/src/Collision/cRigidBody.cpp, mogupro/game/src/Collision/cStaticBlockSimple.cpp, mogupro/game/src/Scene/Member/cGameMain.cpp, mogupro/game/src/gameApp.cpp
コリジョン関係のメンバをカプセル化しました。
ついでにコリジョンワールドも追加しました。
バグってますけど。
=>  GameMainとgameAppを綺麗にしました。

mogupro/game/assets/Shader/simpleShadow.frag, mogupro/game/assets/Shader/simpleShadow.vert, mogupro/game/include/Scene/Member/cGameMain.h, mogupro/game/include/Shader/cShadowManager.h, mogupro/game/src/Scene/Member/cGameMain.cpp, mogupro/game/src/Shader/cShadowManager.cpp
=> 影が自動的につくようになりました。

mogupro/game/include/Network/Packet/Request/cReqCheckBeginGame.h, mogupro/game/include/Network/Packet/Request/cReqWantTeamIn.h, mogupro/game/include/Network/Packet/Response/cResCheckMember.h, mogupro/game/include/Network/Packet/Response/cResWantTeamIn.h, mogupro/game/include/Network/cMatchingMemberManager.h, mogupro/game/include/Scene/Member/cMatching.h, mogupro/game/include/Scene/Member/cMatchingServer.h, mogupro/game/src/Network/Packet/Request/cReqCheckBeginGame.cpp, mogupro/game/src/Network/Packet/Request/cReqWantTeamIn.cpp, mogupro/game/src/Network/Packet/Response/cResWantTeamIn.cpp, mogupro/game/src/Network/cMatchingMemberManager.cpp, mogupro/game/src/Scene/Member/cMatching.cpp, mogupro/game/src/Scene/Member/cMatchingServer.cpp
再送処理、メンバー全員がTeamに入っているかどうかは確認していません
=> Update : とりあえずいろいろと無視した状態ではあるがGameMainにNetworkHandleとTeamIDを送信できるようにした

mogupro/game/assets/Gem/GemManager.frag, mogupro/game/include/Game/Gem/cGem.h, mogupro/game/include/Game/cGemManager.h, mogupro/game/src/Game/Gem/cGem.cpp, mogupro/game/src/Game/cGemManager.cpp, mogupro/game/src/Scene/Member/cGameMain.cpp
cGemにFBO用のdrowを追加しました。
それに伴いGemのシェーダーとcGemManagerのシェーダー関連を書き換えました。
=> cGamMainのFBOの表示をdraw3Dに追加しました。

mogupro/game/include/Game/Gem/cGem.h, mogupro/game/include/Game/cGemManager.h, mogupro/game/src/Game/Gem/cGem.cpp, mogupro/game/src/Game/cGemManager.cpp, mogupro/game/src/Scene/Member/cGameMain.cpp
ジェムを遠くにいるほど発光しないようにしました。
ジェムの生成範囲をチャンクサイズとチャンクの数に比例するようにしました。
=> ジェムの光り方と生成範囲の指定の仕方を変更。

mogupro/game/src/Utility/cInput.cpp, mogupro/game/src/gameApp.cpp
また、インプットでpushKeyをした場合に先のupdateでボタンが回収されてしまっていたので、回収をしないようにしました。
=> deltaが暴れないように、平均をとってupdateを回すようにしました。

mogupro/game/include/Game/cLightManager.h, mogupro/game/src/Game/cLightManager.cpp, mogupro/game/src/Game/cShaderManager.cpp, mogupro/game/src/Scene/Member/cGameMain.cpp
addするとハンドルが返ってくるので使っている間は保存しておいてください。
位置や色を変更する時や、削除するときにも使います。
=> ライトマネージャーが出来ました。

mogupro/game/include/CameraManager/cCameraManager.h, mogupro/game/include/Game/cGameManager.h, mogupro/game/include/Utility/Schedule.h, mogupro/game/include/Utility/cInput.h, mogupro/game/include/Utility/cScheduler.h, mogupro/game/src/CameraManager/cCameraManager.cpp, mogupro/game/src/Game/cGameManager.cpp, mogupro/game/src/Game/cPlayerManager.cpp, mogupro/game/src/Game/cUIManager.cpp, mogupro/game/src/Scene/Member/cGameMain.cpp, mogupro/game/src/Utility/Schedule.cpp, mogupro/game/src/Utility/cInput.cpp, mogupro/game/src/Utility/cScheduler.cpp, mogupro/game/src/gameApp.cpp
決められた時間でステート移動します。
ゲームパッドの更新関数を呼ぶ場所を間違っていたので修正。
スケジューラーを作成。
=> ゲームマネージャーの作成。

mogupro/game/include/Game/Gem/cFragmentGem.h, mogupro/game/include/Game/Gem/cGemStone.h, mogupro/game/include/Game/cGemManager.h, mogupro/game/src/Game/Gem/cFragmentGem.cpp, mogupro/game/src/Game/Gem/cGemStone.cpp, mogupro/game/src/Game/cGemManager.cpp, mogupro/game/src/Scene/Member/cGameMain.cpp
=> GemStoneとFragmentGemにAABB追加。

mogupro/game/include/Collision/cAABBCollider.h, mogupro/game/include/Network/cUDP.h, mogupro/game/include/Scene/cSceneManager.h, mogupro/game/include/Utility/cInput.h, mogupro/game/include/Utility/cSingletonAble.h, mogupro/game/src/CameraManager/cCameraManager.cpp, mogupro/game/src/Collision/cAABBCollider.cpp, mogupro/game/src/Game/cGameManager.cpp, mogupro/game/src/Network/cUDP.cpp, mogupro/game/src/Scene/Member/cGameMain.cpp, mogupro/game/src/Scene/Member/cTitle.cpp, mogupro/game/src/Utility/cInput.cpp
=> ゲームがループするようになりました。

mogupro/game/include/Game/Gem/cFragmentGem.h, mogupro/game/src/Game/Gem/cFragmentGem.cpp, mogupro/game/src/Game/cGemManager.cpp
FragmentGemに重力判定と描画のフラグを作成しました。
=> FBOの遅延によるズレをなくしました。

mogupro/game/include/Sound/Stereophonic.h, mogupro/game/src/Sound/Stereophonic.cpp
=> Stereophonicc

mogupro/game/include/Game/cGemManager.h, mogupro/game/src/Game/Gem/cFragmentGem.cpp
=> cFragGemポイントライトが動くように,

mogupro/game/include/Sound/Stereophonic.h, mogupro/game/src/Sound/Stereophonic.cpp
Update : 立体音響のリスナー位置をカメラに変更
FIx : 立体音響を消す時間を音ごとに変更
=> こんにちは。どうもガクトです

mogupro/game/src/Game/cGemManager.cpp
=> ジェム破壊音を立体に

mogupro/game/include/Sound/Stereophonic.h, mogupro/game/src/Game/Strategy/cCannon.cpp, mogupro/game/src/Game/Weapons/SubWeapon/cLightBomb.cpp, mogupro/game/src/Game/cGemManager.cpp
Update : 立体音響をstringで管理
Fix : 立体音響を生成するたびにWavを作成していたのをなくした
=> てか、うちの家に屋上あんだけど焼いてかない？

mogupro/game/include/Network/cMatchingMemberManager.h, mogupro/game/src/Network/cMatchingMemberManager.cpp, mogupro/game/src/Scene/Member/cMatching.cpp
荒 荒 荒波立つ ここはURBANNITE"ウェカピポ!!"
若 若さの中 不確かな迷いとか"ウェカピポ!!"
逆 逆 逆さまWORLDの 孤独に強く"ウェカピポ!!"
まだ まだ 闘わねば 真実はどこだ"AH AH AH!!"
=> Update : マッチングメンバーのリセット関数を追加
